# The builder will be used to generate the executable (named 'bootstrap')
# which upon invocation will create the necessary 'supervisor.conf' file
FROM golang:1.9.4 as builder

# Copy the local project to the go directory to the container's workspace
ADD . /go/src/github.com/snowdrop/k8s-supervisor

# Specify the directory from where we will build the server
WORKDIR /go/src/github.com/snowdrop/k8s-supervisor/pkg/generator/

# generate executable that will be used by the entrypoint shell script to generate
# the supervisor configuration
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o server server.go

# Copy the application into a thin image
FROM busybox

ARG GENERATOR_DIR=/opt/generator

RUN mkdir -p ${GENERATOR_DIR}/bin

COPY --from=builder /go/src/github.com/snowdrop/k8s-supervisor/pkg/scaffold/config ${GENERATOR_DIR}/
COPY --from=builder /go/src/github.com/snowdrop/k8s-supervisor/pkg/generator/server ${GENERATOR_DIR}/bin/

RUN chgrp -R 0 ${GENERATOR_DIR} && \
    chmod -R g+rwX ${GENERATOR_DIR} && \
    chmod 775 ${GENERATOR_DIR}/bin/server

WORKDIR ${GENERATOR_DIR}
ENTRYPOINT ["/opt/generator/bin/server"]
